<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>GameTracker</AssemblyName>
    <UseWindowsForms>False</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\icon.png" />
    <None Remove="Assets\icon16.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.2.1" />
    <PackageReference Include="WPF-UI.Abstractions" Version="4.2.1" />
    <PackageReference Include="WPF-UI.Tray" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon16.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Screenshots\" />
  </ItemGroup>

</Project>
